### ISSUE TITLE
Support .runsettings

### ISSUE THREAD

**Issue by JFMG** [ademanuele/VSMac-CodeCoverage#3]
Hi there,

is there a support for a .runsettings file? If not, could you please check, it it is possible to add support for .runsettings files?

The official Microsoft documentation for .runsettings files can be found here: https://docs.microsoft.com/de-de/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file?view=vs-2019

**Comment by ademanuele** [comment]
Hello. Thank you for your support suggestion.

As far as I'm aware, .runsettings files are a feature specific to vstest.

What sort of thing are you looking to configure?

**Comment by JFMG** [comment]
I would like to be able to ignore specific files and methods from the code coverage analyses. I use this extension for a Xamarin project and we do not want to include e.g. our Views (.xaml and .xaml.cs files). But also we would like to ignore getter and setter methods because it's not recommended to test them. In my current project we have a test coverage from around 51% and with respect to the .runsettings file a coverage from around 81%.

**Comment by ademanuele** [comment]
I have not had a chance to look into this issue properly. But it seems like it is the VSTest runner built inside Visual Studio for Mac that needs to support using a .runsettings file, rather than this extension.

Having said that, Coverlet, the code coverage provider that this extension uses does have options for excluding/including files/classes which I am currently not using.

I think the best solution for gaining the functionality you want is to surface these options in the extension and potentially having a configuration file that can be stored in your source control to share with others on your team.

I will look into this in a bit more detail soon.

**Comment by ademanuele** [comment]
Unfortunately, there has not been much movement on this yet. I have been quite busy lately.

Am hoping to look into it next week.

**Comment by JFMG** [comment]
I’ll spend you another coffee ☕ , if you do (:

**Comment by subramaniamb** [comment]
+1

**Comment by ademanuele** [comment]
Ok. You've spoken and I've listened.

I've been working on other projects for a while but had some time this weekend to work on this.

I got it working pretty well. Check out v1.1 of the extension and let me know if you have any issues. 🎉

**Comment by JFMG** [comment]
Thanks for the good work 👍

**Comment by ademanuele** [comment]
Work for supporting .runsettings has been done.

Closing this issue.
